# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdb258d7e318b099e998bb7ce79f894c7e4ce75194d77d670df719a7d390facc516b078831df84693e1046a6f3d626d02ac114cc4949d1163d7df97042d9df92

test:
  secret_key_base: 221688416724b63c641ae53e17b69846ad96a5604c735da5792d9c7d67e3a8263c90aeae45b3f832dc4e62614473e71019b8310fc93618fb9ef750e3c31f203f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
